import type { ContactFormInput, ContactFormModal } from '@/types';

const EMPTY_MODAL_DIALOG_CONTACT_FORM: ContactFormModal = {
  id: '',
  url: '',
  title: '',
  subtitle: '',
  submitButtonName: '',
  alertOnSubmit: [],
};

const EMPTY_DIALOG_FORM_INPUT: ContactFormInput[] = [
  {
    id: '',
    input: { id: '', placeholder: '', tag: 'input' },
    label: '',
  },
];

const HISTORY = 100;
const AUTOCOMPLETE = 101;

const SET_INPUT_BORDER_BOX = 'SET_INPUT_BORDER_BOX';
const SET_ERROR_TAG_NAME = 'SET_ERROR_TAG_NAME';
const DELETE_ERROR_TAG_NAME = 'DELETE_ERROR_TAG_NAME';
const SET_INPUT_FOCUS = 'SET_INPUT_FOCUS';
const SET_INPUT_ERROR = 'SET_INPUT_ERROR';
const DELETE_INPUT_ERROR = 'DELETE_INPUT_ERROR';
const SET_AUTO_COMPLETE = 'SET_AUTO_COMPLETE';
const SET_OVERLAY_FIRST_ITEM_FOCUS = 'SET_OVERLAY_FIRST_ITEM_FOCUS';
const RESET_AUTO_COMPLETE_OVERLAY = 'RESET_AUTO_COMPLETE_OVERLAY';
const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
const DELETE_INPUT_VALUE = 'DELETE_INPUT_VALUE';
export {
  EMPTY_MODAL_DIALOG_CONTACT_FORM,
  EMPTY_DIALOG_FORM_INPUT,
  AUTOCOMPLETE,
  HISTORY,
  SET_INPUT_BORDER_BOX,
  SET_ERROR_TAG_NAME,
  DELETE_ERROR_TAG_NAME,
  SET_INPUT_FOCUS,
  SET_INPUT_ERROR,
  DELETE_INPUT_ERROR,
  SET_AUTO_COMPLETE,
  RESET_AUTO_COMPLETE_OVERLAY,
  SET_OVERLAY_FIRST_ITEM_FOCUS,
  SET_INPUT_VALUE,
  DELETE_INPUT_VALUE,
};
