const START = 1;
const PENDING = 2;
const STOP = 3;
const CHANGE_SLIDE = 'CHANGE_SLIDE';
const CHANGE_SCROLLING_DOT = 'CHANGE_SCROLLING_DOT';
const SLIDE_TRANSITION = 'SLIDE_TRANSITION';
const NEXT_SLIDE = 'chevron-forward-outline';
const PREVIOUS_SLIDE = 'chevron-back-outline';
const INIT_MAX_INDEX_SLIDE = 'INIT_MAX_INDEX_SLIDE';

export {
  CHANGE_SCROLLING_DOT,
  CHANGE_SLIDE,
  INIT_MAX_INDEX_SLIDE,
  NEXT_SLIDE,
  PENDING,
  PREVIOUS_SLIDE,
  SLIDE_TRANSITION,
  START,
  STOP,
};
